export interface LaTeXSymbol {
  label: string;
  latex: string;
  category: string;
  tooltip: string;
  scale: number;
}

export const LATEX_CATEGORIES = [
  'Functions',
  'Operators',
  'Relations',
  'Arrows',
  'Brackets',
  'Symbols',
  'Greek',
  'Fonts',
  'Matrices',
  'Environments',
  'Accents'
];

export const LATEX_SYMBOLS = [
  // --- FUNCTIONS: ARITHMETIC & ROOTS ---
  { label: 'Fraction', latex: '\\frac{a}{b}', category: 'Functions', tooltip: 'Fraction: \\frac{a}{b}', scale: 1.6 },
  { label: 'd-Frac', latex: '\\dfrac{a}{b}', category: 'Functions', tooltip: 'Display Fraction: \\dfrac{a}{b}', scale: 1.2 },
  { label: 't-Frac', latex: '\\tfrac{a}{b}', category: 'Functions', tooltip: 'Text Fraction: \\tfrac{a}{b}', scale: 1.4 },
  { label: 'c-Frac', latex: '\\cfrac{a}{1 + \\dots}', category: 'Functions', tooltip: 'Continued Fraction: \\cfrac', scale: 1 },
  { label: 'Sqrt', latex: '\\sqrt{x}', category: 'Functions', tooltip: 'Square Root: \\sqrt{x}', scale: 1.6 },
  { label: 'n-th Sqrt', latex: '\\sqrt[n]{x}', category: 'Functions', tooltip: 'n-th Root: \\sqrt[n]{x}', scale: 1.6 },
  { label: 'Exponent', latex: 'x^{n}', category: 'Functions', tooltip: 'Exponent: x^n', scale: 1.6 },
  { label: 'Subscript', latex: 'x_{n}', category: 'Functions', tooltip: 'Subscript: x_n', scale: 1.6 },

  // --- FUNCTIONS: CALCULUS & ANALYSIS ---
  { label: 'Sum', latex: '\\sum_{i=1}^{n}', category: 'Functions', tooltip: 'Summation: \\sum', scale: 1.2 },
  { label: 'Product', latex: '\\prod_{i=1}^{n}', category: 'Functions', tooltip: 'Product: \\prod', scale: 1.2 },
  { label: 'Coproduct', latex: '\\coprod_{i=1}^{n}', category: 'Functions', tooltip: 'Coproduct: \\coprod', scale: 1.2 },
  { label: 'Integral', latex: '\\int_{a}^{b}', category: 'Functions', tooltip: 'Integral: \\int', scale: 1.4 },
  { label: 'Double Int', latex: '\\iint_{D}', category: 'Functions', tooltip: 'Double Integral: \\iint', scale: 1.4 },
  { label: 'Triple Int', latex: '\\iiint_{V}', category: 'Functions', tooltip: 'Triple Integral: \\iiint', scale: 1.4 },
  { label: 'Contour Int', latex: '\\oint_{C}', category: 'Functions', tooltip: 'Contour Integral: \\oint', scale: 1.4 },
  { label: 'Surf Int', latex: '\\oiint_{S}', category: 'Functions', tooltip: 'Surface Integral: \\oiint', scale: 1.4 },
  { label: 'Vol Int', latex: '\\oiiint_{V}', category: 'Functions', tooltip: 'Volume Integral: \\oiiint', scale: 1.4 },
  { label: 'Intop', latex: '\\intop', category: 'Functions', tooltip: 'Integral with limits above/below', scale: 1.4 },
  { label: 'Small Int', latex: '\\smallint', category: 'Functions', tooltip: 'Small Integral Symbol', scale: 1.4 },
  { label: 'Partial', latex: '\\partial', category: 'Functions', tooltip: 'Partial Derivative Symbol', scale: 1.8 },
  { label: 'Deriv', latex: '\\frac{d }{dx}', category: 'Functions', tooltip: 'Derivative: \\frac{d}{dx}', scale: 1.6 },
  { label: 'PDeriv', latex: '\\frac{\\partial }{\\partial x}', category: 'Functions', tooltip: 'Partial Derivative: \\frac{\\partial}{\\partial x}', scale: 1.6 },
  { label: 'Limit', latex: '\\lim_{x \\to \\infty}', category: 'Functions', tooltip: 'Limit: \\lim', scale: 1 },
  { label: 'lim inf', latex: '\\liminf', category: 'Functions', tooltip: 'Limit Infimum', scale: 1.1 },
  { label: 'lim sup', latex: '\\limsup', category: 'Functions', tooltip: 'Limit Supremum', scale: 1.1 },
  { label: 'inj lim', latex: '\\injlim', category: 'Functions', tooltip: 'Injective Limit', scale: 1.1 },
  { label: 'proj lim', latex: '\\projlim', category: 'Functions', tooltip: 'Projective Limit', scale: 1.1 },
  { label: 'var inj lim', latex: '\\varinjlim', category: 'Functions', tooltip: 'Variant Injective Limit', scale: 1.4 },
  { label: 'var proj lim', latex: '\\varprojlim', category: 'Functions', tooltip: 'Variant Projective Limit', scale: 1.4 },
  { label: 'var lim inf', latex: '\\varliminf', category: 'Functions', tooltip: 'Variant Limit Infimum', scale: 1.4 },
  { label: 'var lim sup', latex: '\\varlimsup', category: 'Functions', tooltip: 'Variant Limit Supremum', scale: 1.4 },
  { label: 'plim', latex: '\\plim', category: 'Functions', tooltip: 'Probability Limit', scale: 1.4 },

  // --- FUNCTIONS: BIG OPERATORS ---
  { label: '⋃', latex: '\\bigcup_{i=1}^{n}', category: 'Functions', tooltip: 'Big Union', scale: 1.2 },
  { label: '⋂', latex: '\\bigcap_{i=1}^{n}', category: 'Functions', tooltip: 'Big Intersection', scale: 1.2 },
  { label: '⋁', latex: '\\bigvee_{i=1}^{n}', category: 'Functions', tooltip: 'Big OR', scale: 1.2 },
  { label: '⋀', latex: '\\bigwedge_{i=1}^{n}', category: 'Functions', tooltip: 'Big AND', scale: 1.2 },
  { label: '⨁', latex: '\\bigoplus_{i=1}^{n}', category: 'Functions', tooltip: 'Big O-Plus', scale: 1.2 },
  { label: '⨂', latex: '\\bigotimes_{i=1}^{n}', category: 'Functions', tooltip: 'Big O-Times', scale: 1.2 },
  { label: '⨀', latex: '\\bigodot_{i=1}^{n}', category: 'Functions', tooltip: 'Big O-Dot', scale: 1.2 },
  { label: '⨄', latex: '\\biguplus_{i=1}^{n}', category: 'Functions', tooltip: 'Big U-Plus', scale: 1.2 },
  { label: '⨆', latex: '\\bigsqcup_{i=1}^{n}', category: 'Functions', tooltip: 'Big Square Cup', scale: 1.2 },

  // --- FUNCTIONS: COMBINATORICS ---
  { label: 'nCr', latex: '\\mathrm{C}_{n}^{k}', category: 'Functions', tooltip: 'Combination (nCr)', scale: 1.4 },
  { label: 'binom', latex: '\\binom{n}{k}', category: 'Functions', tooltip: 'Binomial Coefficient', scale: 1.4 },
  { label: 'd-binom', latex: '\\dbinom{n}{k}', category: 'Functions', tooltip: 'Display Binomial', scale: 1 },
  { label: 't-binom', latex: '\\tbinom{n}{k}', category: 'Functions', tooltip: 'Text Binomial', scale: 1.6 },
  { label: '{ }', latex: '{n \\brace k}', category: 'Functions', tooltip: 'Stirling numbers (second kind)', scale: 1.4 },
  { label: '[ ]', latex: '{n \\brack k}', category: 'Functions', tooltip: 'Stirling numbers (first kind)', scale: 1.4 },

  // --- FUNCTIONS: TRIGONOMETRY ---
  { label: 'sin', latex: '\\sin', category: 'Functions', tooltip: 'Sine', scale: 1.4 },
  { label: 'cos', latex: '\\cos', category: 'Functions', tooltip: 'Cosine', scale: 1.4 },
  { label: 'tan', latex: '\\tan', category: 'Functions', tooltip: 'Tangent', scale: 1.4 },
  { label: 'cot', latex: '\\cot', category: 'Functions', tooltip: 'Cotangent', scale: 1.4 },
  { label: 'sec', latex: '\\sec', category: 'Functions', tooltip: 'Secant', scale: 1.4 },
  { label: 'csc', latex: '\\csc', category: 'Functions', tooltip: 'Cosecant', scale: 1.4 },
  { label: 'cosec', latex: '\\cosec', category: 'Functions', tooltip: 'Cosecant variant', scale: 1.4 },
  { label: 'arcsin', latex: '\\arcsin', category: 'Functions', tooltip: 'Arcsine', scale: 1.2 },
  { label: 'arccos', latex: '\\arccos', category: 'Functions', tooltip: 'Arccosine', scale: 1.2 },
  { label: 'arctan', latex: '\\arctan', category: 'Functions', tooltip: 'Arctangent', scale: 1.2 },
  { label: 'arcctg', latex: '\\arcctg', category: 'Functions', tooltip: 'Arccotangent', scale: 1.2 },
  { label: 'arctg', latex: '\\arctg', category: 'Functions', tooltip: 'Arctangent variant', scale: 1.2 },
  { label: 'tg', latex: '\\tg', category: 'Functions', tooltip: 'Tangent variant', scale: 1.4 },
  { label: 'ctg', latex: '\\ctg', category: 'Functions', tooltip: 'Cotangent variant', scale: 1.4 },

  // --- FUNCTIONS: HYPERBOLIC ---
  { label: 'sinh', latex: '\\sinh', category: 'Functions', tooltip: 'Hyperbolic Sine', scale: 1.4 },
  { label: 'cosh', latex: '\\cosh', category: 'Functions', tooltip: 'Hyperbolic Cosine', scale: 1.4 },
  { label: 'tanh', latex: '\\tanh', category: 'Functions', tooltip: 'Hyperbolic Tangent', scale: 1.4 },
  { label: 'coth', latex: '\\coth', category: 'Functions', tooltip: 'Hyperbolic Cotangent', scale: 1.4 },
  { label: 'sh', latex: '\\sh', category: 'Functions', tooltip: 'Hyperbolic Sine variant', scale: 1.4 },
  { label: 'ch', latex: '\\ch', category: 'Functions', tooltip: 'Hyperbolic Cosine variant', scale: 1.4 },
  { label: 'th', latex: '\\th', category: 'Functions', tooltip: 'Hyperbolic Tangent variant', scale: 1.4 },
  { label: 'cth', latex: '\\cth', category: 'Functions', tooltip: 'Hyperbolic Cotangent variant', scale: 1.4 },

  // --- FUNCTIONS: LOGARITHMS & MISC ---
  { label: 'Log', latex: '\\log_{b}(x)', category: 'Functions', tooltip: 'Logarithm with base', scale: 1.2 },
  { label: 'log', latex: '\\log', category: 'Functions', tooltip: 'Logarithm', scale: 1.4 },
  { label: 'Ln', latex: '\\ln(x)', category: 'Functions', tooltip: 'Natural Logarithm with x', scale: 1.4 },
  { label: 'ln', latex: '\\ln', category: 'Functions', tooltip: 'Natural Logarithm', scale: 1.4 },
  { label: 'lg', latex: '\\lg', category: 'Functions', tooltip: 'Common Logarithm', scale: 1.4 },
  { label: 'exp', latex: '\\exp', category: 'Functions', tooltip: 'Exponential', scale: 1.4 },
  { label: 'det', latex: '\\det', category: 'Functions', tooltip: 'Determinant', scale: 1.4 },
  { label: 'dim', latex: '\\dim', category: 'Functions', tooltip: 'Dimension', scale: 1.4 },
  { label: 'gcd', latex: '\\gcd', category: 'Functions', tooltip: 'Greatest Common Divisor', scale: 1.4 },
  { label: 'ker', latex: '\\ker', category: 'Functions', tooltip: 'Kernel', scale: 1.4 },
  { label: 'hom', latex: '\\hom', category: 'Functions', tooltip: 'Homomorphism', scale: 1.4 },
  { label: 'Pr', latex: '\\Pr', category: 'Functions', tooltip: 'Probability', scale: 1.4 },
  { label: 'max', latex: '\\max', category: 'Functions', tooltip: 'Maximum', scale: 1.4 },
  { label: 'min', latex: '\\min', category: 'Functions', tooltip: 'Minimum', scale: 1.4 },
  { label: 'sup', latex: '\\sup', category: 'Functions', tooltip: 'Supremum', scale: 1.4 },
  { label: 'inf', latex: '\\inf', category: 'Functions', tooltip: 'Infimum', scale: 1.4 },
  { label: 'argmax', latex: '\\argmax', category: 'Functions', tooltip: 'Argument of Maximum', scale: 1.1 },
  { label: 'argmin', latex: '\\argmin', category: 'Functions', tooltip: 'Argument of Minimum', scale: 1.1 },
  { label: 'arg', latex: '\\arg', category: 'Functions', tooltip: 'Argument', scale: 1.4 },
  { label: 'deg', latex: '\\deg', category: 'Functions', tooltip: 'Degree', scale: 1.4 },
  { label: 'op', latex: '\\operatorname{f}', category: 'Functions', tooltip: 'Custom Operator', scale: 1.4 },


  // --- OPERATORS: STANDARD ARITHMETIC ---
  { label: '+', latex: '+', category: 'Operators', tooltip: 'Add', scale: 2 },
  { label: '-', latex: '-', category: 'Operators', tooltip: 'Subtract', scale: 2 },
  { label: '±', latex: '\\pm', category: 'Operators', tooltip: 'Plus-Minus', scale: 2 },
  { label: '∓', latex: '\\mp', category: 'Operators', tooltip: 'Minus-Plus', scale: 2 },
  { label: '×', latex: '\\times', category: 'Operators', tooltip: 'Multiplication (Cross)', scale: 2 },
  { label: '÷', latex: '\\div', category: 'Operators', tooltip: 'Division', scale: 2 },
  { label: '/', latex: '/', category: 'Operators', tooltip: 'Slash', scale: 1.6 },
  { label: '⋅', latex: '\\cdot', category: 'Operators', tooltip: 'Dot Product', scale: 2.6 },
  { label: 'centerdot', latex: '\\centerdot', category: 'Operators', tooltip: 'Center Dot', scale: 1.8 },
  { label: '∗', latex: '\\ast', category: 'Operators', tooltip: 'Asterisk Operator', scale: 2 },
  { label: '⋆', latex: '\\star', category: 'Operators', tooltip: 'Star Operator', scale: 2 },
  { label: '∘', latex: '\\circ', category: 'Operators', tooltip: 'Composition Circle', scale: 2 },
  { label: '∙', latex: '\\bullet', category: 'Operators', tooltip: 'Bullet Point', scale: 2 },
  { label: 'ldotp', latex: '\\ldotp', category: 'Operators', tooltip: 'Lower Dot Punctuation', scale: 2 },
  { label: 'cdotp', latex: '\\cdotp', category: 'Operators', tooltip: 'Center Dot Punctuation', scale: 2 },

  // --- OPERATORS: SET THEORY & LATTICE ---
  { label: '∩', latex: '\\cap', category: 'Operators', tooltip: 'Intersection', scale: 2 },
  { label: '∪', latex: '\\cup', category: 'Operators', tooltip: 'Union', scale: 2 },
  { label: '⊎', latex: '\\uplus', category: 'Operators', tooltip: 'Multiset Union', scale: 2 },
  { label: '⊓', latex: '\\sqcap', category: 'Operators', tooltip: 'Square Cap', scale: 2 },
  { label: '⊔', latex: '\\sqcup', category: 'Operators', tooltip: 'Square Cup', scale: 2 },
  { label: '∖', latex: '\\setminus', category: 'Operators', tooltip: 'Set Minus', scale: 1.6 },
  { label: '∖', latex: '\\smallsetminus', category: 'Operators', tooltip: 'Small Set Minus', scale: 1.6 },
  { label: '≀', latex: '\\wr', category: 'Operators', tooltip: 'Wreath Product', scale: 2 },
  { label: '∐', latex: '\\amalg', category: 'Operators', tooltip: 'Amalgamation', scale: 2 },
  { label: '⋒', latex: '\\Cap', category: 'Operators', tooltip: 'Double Cap', scale: 2 },
  { label: '⋓', latex: '\\Cup', category: 'Operators', tooltip: 'Double Cup', scale: 2 },
  { label: '⋒', latex: '\\doublecap', category: 'Operators', tooltip: 'Double Cap variant', scale: 2 },
  { label: '⋓', latex: '\\doublecup', category: 'Operators', tooltip: 'Double Cup variant', scale: 2 },

  // --- OPERATORS: LOGIC & CONNECTIVES ---
  { label: '∧', latex: '\\wedge', category: 'Operators', tooltip: 'Logical AND (wedge)', scale: 2 },
  { label: '∨', latex: '\\vee', category: 'Operators', tooltip: 'Logical OR (vee)', scale: 2 },
  { label: '∧', latex: '\\land', category: 'Operators', tooltip: 'Logical AND', scale: 2 },
  { label: '∨', latex: '\\lor', category: 'Operators', tooltip: 'Logical OR', scale: 2 },
  { label: '&', latex: '\\And', category: 'Operators', tooltip: 'Logical AND Symbol', scale: 1.8 },
  { label: '⋏', latex: '\\curlywedge', category: 'Operators', tooltip: 'Curly Wedge', scale: 2 },
  { label: '⋎', latex: '\\curlyvee', category: 'Operators', tooltip: 'Curly Vee', scale: 2 },
  { label: '⊼', latex: '\\barwedge', category: 'Operators', tooltip: 'Bar Wedge', scale: 2 },
  { label: '⩞', latex: '\\doublebarwedge', category: 'Operators', tooltip: 'Double Bar Wedge', scale: 2 },
  { label: '⊻', latex: '\\veebar', category: 'Operators', tooltip: 'Vee Bar', scale: 2 },

  // --- OPERATORS: CIRCLED & BOXED ---
  { label: '⊕', latex: '\\oplus', category: 'Operators', tooltip: 'Circled Plus', scale: 2 },
  { label: '⊖', latex: '\\ominus', category: 'Operators', tooltip: 'Circled Minus', scale: 2 },
  { label: '⊗', latex: '\\otimes', category: 'Operators', tooltip: 'Circled Times', scale: 2 },
  { label: '⊘', latex: '\\oslash', category: 'Operators', tooltip: 'Circled Slash', scale: 2 },
  { label: '⊙', latex: '\\odot', category: 'Operators', tooltip: 'Circled Dot', scale: 2 },
  { label: '⊛', latex: '\\circledast', category: 'Operators', tooltip: 'Circled Asterisk', scale: 2 },
  { label: '⊚', latex: '\\circledcirc', category: 'Operators', tooltip: 'Circled Circle', scale: 2 },
  { label: '⊝', latex: '\\circleddash', category: 'Operators', tooltip: 'Circled Dash', scale: 2 },
  { label: 'box+', latex: '\\boxplus', category: 'Operators', tooltip: 'Boxed Plus', scale: 2 },
  { label: 'box-', latex: '\\boxminus', category: 'Operators', tooltip: 'Boxed Minus', scale: 2 },
  { label: 'box*', latex: '\\boxtimes', category: 'Operators', tooltip: 'Boxed Times', scale: 2 },
  { label: 'box.', latex: '\\boxdot', category: 'Operators', tooltip: 'Boxed Dot', scale: 2 },

  // --- OPERATORS: TRIANGULAR & MISC ---
  { label: '⊲', latex: '\\lhd', category: 'Operators', tooltip: 'Left Hand Triangle', scale: 2 },
  { label: '⊳', latex: '\\rhd', category: 'Operators', tooltip: 'Right Hand Triangle', scale: 2 },
  { label: '⊴', latex: '\\unlhd', category: 'Operators', tooltip: 'Underlined Left Triangle', scale: 2 },
  { label: '⊵', latex: '\\unrhd', category: 'Operators', tooltip: 'Underlined Right Triangle', scale: 2 },
  { label: '†', latex: '\\dagger', category: 'Operators', tooltip: 'Dagger', scale: 1.8 },
  { label: '‡', latex: '\\ddagger', category: 'Operators', tooltip: 'Double Dagger', scale: 1.8 },
  { label: '⊺', latex: '\\intercal', category: 'Operators', tooltip: 'Intercal (Transpose)', scale: 1.8 },
  { label: '∔', latex: '\\dotplus', category: 'Operators', tooltip: 'Dot Plus', scale: 2 },
  { label: '⋇', latex: '\\divideontimes', category: 'Operators', tooltip: 'Divide on Times', scale: 2 },
  { label: '◯', latex: '\\bigcirc', category: 'Operators', tooltip: 'Large Circle', scale: 1.6 },
  { label: '⋗', latex: '\\gtrdot', category: 'Operators', tooltip: 'Greater than Dot', scale: 2 },
  { label: '⋖', latex: '\\lessdot', category: 'Operators', tooltip: 'Less than Dot', scale: 2 },

  // --- OPERATORS: MODULO ---
  { label: 'mod', latex: '\\bmod', category: 'Operators', tooltip: 'Modulo', scale: 1.4 },

  // --- OPERATORS: PRODUCTS ---
  { label: '⋉', latex: '\\ltimes', category: 'Operators', tooltip: 'Left Semidirect Product', scale: 2 },
  { label: '⋊', latex: '\\rtimes', category: 'Operators', tooltip: 'Right Semidirect Product', scale: 2 },
  { label: '⋋', latex: '\\leftthreetimes', category: 'Operators', tooltip: 'Left Three Times', scale: 2 },
  { label: '⋌', latex: '\\rightthreetimes', category: 'Operators', tooltip: 'Right Three Times', scale: 2 },
  { label:'⋓', latex: '\\doublecup', category: 'Operators', tooltip: 'Double Cup', scale: 2 },


  // --- RELATIONS ---
  { label: '=', latex: '=', category: 'Relations', tooltip: 'Equal', scale: 1.8 },
  { label: '≠', latex: '\\neq', category: 'Relations', tooltip: 'Not Equal', scale: 1.8 },
  { label: '≡', latex: '\\equiv', category: 'Relations', tooltip: 'Equivalent', scale: 1.8 },
  { label: '≢', latex: '\\not\\equiv', category: 'Relations', tooltip: 'Not Equivalent', scale: 1.8 },
  { label: '≈', latex: '\\approx', category: 'Relations', tooltip: 'Approximately Equal', scale: 1.8 },
  { label: '≃', latex: '\\simeq', category: 'Relations', tooltip: 'Asymptotically Equal', scale: 1.8 },
  { label: '∼', latex: '\\sim', category: 'Relations', tooltip: 'Similar', scale: 1.8 },
  { label: '≁', latex: '\\nsim', category: 'Relations', tooltip: 'Not Similar', scale: 1.8 },
  { label: '≅', latex: '\\cong', category: 'Relations', tooltip: 'Congruent', scale: 1.8 },
  { label: '≇', latex: '\\ncong', category: 'Relations', tooltip: 'Not Congruent', scale: 1.8 },
  { label: '∝', latex: '\\propto', category: 'Relations', tooltip: 'Proportional', scale: 1.8 },
  { label: '<', latex: '<', category: 'Relations', tooltip: 'Less Than', scale: 1.8 },
  { label: '>', latex: '>', category: 'Relations', tooltip: 'Greater Than', scale: 1.8 },
  { label: '≤', latex: '\\le', category: 'Relations', tooltip: 'Less Than or Equal', scale: 1.8 },
  { label: '≥', latex: '\\ge', category: 'Relations', tooltip: 'Greater Than or Equal', scale: 1.8 },
  { label: '⩽', latex: '\\leqslant', category: 'Relations', tooltip: 'Less Than or Slanted Equal', scale: 1.8 },
  { label: '⩾', latex: '\\geqslant', category: 'Relations', tooltip: 'Greater Than or Slanted Equal', scale: 1.8 },
  { label: '≪', latex: '\\ll', category: 'Relations', tooltip: 'Much Less Than', scale: 1.8 },
  { label: '≫', latex: '\\gg', category: 'Relations', tooltip: 'Much Greater Than', scale: 1.8 },
  { label: '≲', latex: '\\lesssim', category: 'Relations', tooltip: 'Less Than or Similar', scale: 1.8 },
  { label: '≳', latex: '\\gtrsim', category: 'Relations', tooltip: 'Greater Than or Similar', scale: 1.8 },
  { label: '⊂', latex: '\\subset', category: 'Relations', tooltip: 'Proper Subset', scale: 1.8 },
  { label: '⊃', latex: '\\supset', category: 'Relations', tooltip: 'Proper Superset', scale: 1.8 },
  { label: '⊆', latex: '\\subseteq', category: 'Relations', tooltip: 'Subset or Equal', scale: 1.8 },
  { label: '⫋', latex: '\\subsetneq', category: 'Relations', tooltip: 'Subset and Not Equal', scale: 1.8 },
  { label: '⊇', latex: '\\supseteq', category: 'Relations', tooltip: 'Superset or Equal', scale: 1.8 },
  { label: '∈', latex: '\\in', category: 'Relations', tooltip: 'Element of', scale: 1.8 },
  { label: '∋', latex: '\\ni', category: 'Relations', tooltip: 'Contains as element', scale: 1.8 },
  { label: '∉', latex: '\\notin', category: 'Relations', tooltip: 'Not an element of', scale: 1.8 },
  { label: '⊢', latex: '\\vdash', category: 'Relations', tooltip: 'Turnstile / Entails', scale: 1.8 },
  { label: '⊣', latex: '\\dashv', category: 'Relations', tooltip: 'Antiturnstile', scale: 1.8 },
  { label: '⊨', latex: '\\models', category: 'Relations', tooltip: 'Models', scale: 1.8 },
  { label: '⊥', latex: '\\perp', category: 'Relations', tooltip: 'Perpendicular', scale: 1.8 },
  { label: '∥', latex: '\\parallel', category: 'Relations', tooltip: 'Parallel', scale: 1.8 },
  { label: '∣', latex: '\\mid', category: 'Relations', tooltip: 'Divide / Mid', scale: 1.8 },
  { label: '∤', latex: '\\nmid', category: 'Relations', tooltip: 'Not Divide', scale: 1.8 },
  { label: '≼', latex: '\\preccurlyeq', category: 'Relations', tooltip: 'Precedes or Equal', scale: 1.8 },
  { label: '≽', latex: '\\succcurlyeq', category: 'Relations', tooltip: 'Succeeds or Equal', scale: 1.8 },
  { label: '≺', latex: '\\prec', category: 'Relations', tooltip: 'Precedes', scale: 1.8 },
  { label: '≻', latex: '\\succ', category: 'Relations', tooltip: 'Succeeds', scale: 1.8 },
  { label: '⋈', latex: '\\bowtie', category: 'Relations', tooltip: 'Bowtie Join', scale: 1.8 },
  { label: '≍', latex: '\\asymp', category: 'Relations', tooltip: 'Asymptotically equivalent', scale: 1.8 },
  { label: '≐', latex: '\\doteq', category: 'Relations', tooltip: 'Dot Equal', scale: 1.8 },
  { label: '≑', latex: '\\doteqdot', category: 'Relations', tooltip: 'Double Dot Equal', scale: 1.8 },
  { label: '≒', latex: '\\fallingdotseq', category: 'Relations', tooltip: 'Falling Dot Equal', scale: 1.8 },
  { label: '≓', latex: '\\risingdotseq', category: 'Relations', tooltip: 'Rising Dot Equal', scale: 1.8 },
  { label: '⪅', latex: '\\lessapprox', category: 'Relations', tooltip: 'Less than approx', scale: 1.8 },
  { label: '⪆', latex: '\\gtrapprox', category: 'Relations', tooltip: 'Greater than approx', scale: 1.8 },
  { label: '≂', latex: '\\eqsim', category: 'Relations', tooltip: 'Equal similar', scale: 1.8 },
  { label: '≊', latex: '\\approxeq', category: 'Relations', tooltip: 'Approx equal', scale: 1.8 },
  { label: '≏', latex: '\\bumpeq', category: 'Relations', tooltip: 'Bump equal', scale: 1.8 },
  { label: '≎', latex: '\\Bumpeq', category: 'Relations', tooltip: 'Big Bump equal', scale: 1.8 },
  { label: '⋚', latex: '\\lesseqgtr', category: 'Relations', tooltip: 'Less equal gtr', scale: 1.8 },
  { label: '⋛', latex: '\\gtreqless', category: 'Relations', tooltip: 'Gtr equal less', scale: 1.8 },
  { label: '⪖', latex: '\\eqslantgtr', category: 'Relations', tooltip: 'Eq slant gtr', scale: 1.8 },
  { label: '⪕', latex: '\\eqslantless', category: 'Relations', tooltip: 'Eq slant less', scale: 1.8 },
  { label: '⋐', latex: '\\Subset', category: 'Relations', tooltip: 'Double Subset', scale: 1.8 },
  { label: '⋑', latex: '\\Supset', category: 'Relations', tooltip: 'Double Superset', scale: 1.8 },
  { label: '∍', latex: '\\backepsilon', category: 'Relations', tooltip: 'Back Epsilon', scale: 1.8 },
  { label: '∽', latex: '\\backsim', category: 'Relations', tooltip: 'Back Sim', scale: 1.8 },
  { label: '⋍', latex: '\\backsimeq', category: 'Relations', tooltip: 'Back Simeq', scale: 1.8 },
  { label: '≬', latex: '\\between', category: 'Relations', tooltip: 'Between', scale: 1.8 },
  { label: '⋔', latex: '\\pitchfork', category: 'Relations', tooltip: 'Pitchfork', scale: 1.8 },
  { label: '⊸', latex: '\\multimap', category: 'Relations', tooltip: 'Multimap', scale: 1.8 },
  { label: '⌢', latex: '\\frown', category: 'Relations', tooltip: 'Frown', scale: 1.8 },
  { label: '⌣', latex: '\\smile', category: 'Relations', tooltip: 'Smile', scale: 1.8 },
  { label: '≗', latex: '\\circeq', category: 'Relations', tooltip: 'Circle Equal', scale: 1.8 },

  // --- ARROWS ---
  { label: '→', latex: '\\to', category: 'Arrows', tooltip: 'Right Arrow', scale: 1.8 },
  { label: '←', latex: '\\gets', category: 'Arrows', tooltip: 'Left Arrow', scale: 1.8 },
  { label: '↔', latex: '\\leftrightarrow', category: 'Arrows', tooltip: 'Left-Right Arrow', scale: 1.8 },
  { label: '⇒', latex: '\\Rightarrow', category: 'Arrows', tooltip: 'Implies', scale: 1.8 },
  { label: '⇐', latex: '\\Leftarrow', category: 'Arrows', tooltip: 'Left Implies', scale: 1.8 },
  { label: '⇔', latex: '\\Leftrightarrow', category: 'Arrows', tooltip: 'Iff', scale: 1.8 },
  { label: '↑', latex: '\\uparrow', category: 'Arrows', tooltip: 'Up Arrow', scale: 1.6 },
  { label: '↓', latex: '\\downarrow', category: 'Arrows', tooltip: 'Down Arrow', scale: 1.6 },
  { label: '↕', latex: '\\updownarrow', category: 'Arrows', tooltip: 'Up-Down Arrow', scale: 1.6 },
  { label: '↗', latex: '\\nearrow', category: 'Arrows', tooltip: 'Up-Right Arrow', scale: 1.6 },
  { label: '↘', latex: '\\searrow', category: 'Arrows', tooltip: 'Down-Right Arrow', scale: 1.6 },
  { label: '↙', latex: '\\swarrow', category: 'Arrows', tooltip: 'Down-Left Arrow', scale: 1.6 },
  { label: '↖', latex: '\\nwarrow', category: 'Arrows', tooltip: 'Up-Left Arrow', scale: 1.6 },
  { label: '⇉', latex: '\\rightrightarrows', category: 'Arrows', tooltip: 'Double Right Arrows', scale: 1.8 },
  { label: '⇈', latex: '\\upuparrows', category: 'Arrows', tooltip: 'Double Up Arrows', scale: 1.8 },
  { label: '⇌', latex: '\\rightleftharpoons', category: 'Arrows', tooltip: 'Equilibrium Harpoons', scale: 1.8 },
  { label: '⇋', latex: '\\leftrightharpoons', category: 'Arrows', tooltip: 'Reverse Equilibrium Harpoons', scale: 1.8 },
  { label: '↪', latex: '\\hookrightarrow', category: 'Arrows', tooltip: 'Hooked Right Arrow', scale: 1.8 },
  { label: '↩', latex: '\\hookleftarrow', category: 'Arrows', tooltip: 'Hooked Left Arrow', scale: 1.8 },
  { label: '↣', latex: '\\rightarrowtail', category: 'Arrows', tooltip: 'Right Arrow Tail', scale: 1.8 },
  { label: '⇝', latex: '\\rightsquigarrow', category: 'Arrows', tooltip: 'Squiggly Right Arrow', scale: 1.8 },
  { label: '↷', latex: '\\curvearrowright', category: 'Arrows', tooltip: 'Curve Arrow Right', scale: 1.8 },
  { label: '↶', latex: '\\curvearrowleft', category: 'Arrows', tooltip: 'Curve Arrow Left', scale: 1.8 },
  { label: '↻', latex: '\\circlearrowright', category: 'Arrows', tooltip: 'Circle Arrow Right', scale: 1.8 },
  { label: '⟶', latex: '\\longrightarrow', category: 'Arrows', tooltip: 'Long Right Arrow', scale: 1.4 },
  { label: '⟵', latex: '\\longleftarrow', category: 'Arrows', tooltip: 'Long Left Arrow', scale: 1.4 },
  { label: '⟷', latex: '\\longleftrightarrow', category: 'Arrows', tooltip: 'Long Left-Right Arrow', scale: 1.4 },
  { label: '⟹', latex: '\\Longrightarrow', category: 'Arrows', tooltip: 'Long Implies', scale: 1.4 },
  { label: '⟸', latex: '\\Longleftarrow', category: 'Arrows', tooltip: 'Long Back Implies', scale: 1.4 },
  { label: '⟺', latex: '\\Longleftrightarrow', category: 'Arrows', tooltip: 'Long Iff', scale: 1.4 },
  { label: '↦', latex: '\\mapsto', category: 'Arrows', tooltip: 'Maps To', scale: 1.8 },
  { label: '⟼', latex: '\\longmapsto', category: 'Arrows', tooltip: 'Long Maps To', scale: 1.4 },
  { label: '⇑', latex: '\\Uparrow', category: 'Arrows', tooltip: 'Double Up Arrow', scale: 1.6 },
  { label: '⇓', latex: '\\Downarrow', category: 'Arrows', tooltip: 'Double Down Arrow', scale: 1.6 },
  { label: '⇕', latex: '\\Updownarrow', category: 'Arrows', tooltip: 'Double Up-Down Arrow', scale: 1.6 },
  { label: '↺', latex: '\\circlearrowleft', category: 'Arrows', tooltip: 'Circle Arrow Left', scale: 1.8 },
  { label: 'loop', latex: '\\looparrowright', category: 'Arrows', tooltip: 'Loop Arrow Right', scale: 1.8 },
  { label: '⇝', latex: '\\leftrightsquigarrow', category: 'Arrows', tooltip: 'Squiggly Left-Right Arrow', scale: 1.8 },

  // --- BRACKETS ---
  { label: '( )', latex: '\\left( x \\right)', category: 'Brackets', tooltip: 'Parentheses', scale: 1.6 },
  { label: '[ ]', latex: '\\left[ x \\right]', category: 'Brackets', tooltip: 'Square Brackets', scale: 1.6 },
  { label: '{ }', latex: '\\left\\{ x \\right\\}', category: 'Brackets', tooltip: 'Curly Braces', scale: 1.6 },
  { label: '⟨ ⟩', latex: '\\left\\langle x \\right\\rangle', category: 'Brackets', tooltip: 'Angle Brackets', scale: 1.6 },
  { label: '| |', latex: '\\left| x \\right|', category: 'Brackets', tooltip: 'Absolute Value', scale: 1.6 },
  { label: '‖ ‖', latex: '\\left\\| x \\right\\|', category: 'Brackets', tooltip: 'Norm', scale: 1.6 },
  { label: '⌈ ⌉', latex: '\\lceil x \\rceil', category: 'Brackets', tooltip: 'Ceiling', scale: 1.6 },
  { label: '⌊ ⌋', latex: '\\lfloor x \\rfloor', category: 'Brackets', tooltip: 'Floor', scale: 1.6 },
  { label: '⟦ ⟧', latex: '\\llbracket x \\rrbracket', category: 'Brackets', tooltip: 'Double Brackets', scale: 1.6 },
  { label: '⦃ ⦄', latex: '\\lBrace x \\rBrace', category: 'Brackets', tooltip: 'White Braces', scale: 1.6 },

  // --- SYMBOLS ---
  { label: '∞', latex: '\\infty', category: 'Symbols', tooltip: 'Infinity', scale: 1.8 },
  { label: '∇', latex: '\\nabla', category: 'Symbols', tooltip: 'Nabla / Gradient', scale: 1.8 },
  { label: '∀', latex: '\\forall', category: 'Symbols', tooltip: 'For All', scale: 1.8 },
  { label: '∃', latex: '\\exists', category: 'Symbols', tooltip: 'Exists', scale: 1.8 },
  { label: '∄', latex: '\\nexists', category: 'Symbols', tooltip: 'Not Exists', scale: 1.8 },
  { label: '∅', latex: '\\emptyset', category: 'Symbols', tooltip: 'Empty Set', scale: 1.8 },
  { label: 'ℏ', latex: '\\hbar', category: 'Symbols', tooltip: 'Reduced Planck Constant', scale: 1.8 },
  { label: 'ℓ', latex: '\\ell', category: 'Symbols', tooltip: 'Script L', scale: 1.8 },
  { label: 'ℜ', latex: '\\Re', category: 'Symbols', tooltip: 'Real Part', scale: 1.8 },
  { label: 'ℑ', latex: '\\Im', category: 'Symbols', tooltip: 'Imaginary Part', scale: 1.8 },
  { label: 'ı', latex: '\\imath', category: 'Symbols', tooltip: 'Dotless i', scale: 1.8 },
  { label: 'ȷ', latex: '\\jmath', category: 'Symbols', tooltip: 'Dotless j', scale: 1.8 },
  { label: '∠', latex: '\\angle', category: 'Symbols', tooltip: 'Angle', scale: 1.8 },
  { label: '∡', latex: '\\measuredangle', category: 'Symbols', tooltip: 'Measured Angle', scale: 1.8 },
  { label: '∢', latex: '\\sphericalangle', category: 'Symbols', tooltip: 'Spherical Angle', scale: 1.8 },
  { label: 'ð', latex: '\\eth', category: 'Symbols', tooltip: 'Eth Symbol', scale: 1.8 },
  { label: '℘', latex: '\\wp', category: 'Symbols', tooltip: 'Weierstrass p', scale: 1.8 },
  { label: 'ℵ', latex: '\\aleph', category: 'Symbols', tooltip: 'Aleph', scale: 1.8 },
  { label: 'ℶ', latex: '\\beth', category: 'Symbols', tooltip: 'Beth', scale: 1.8 },
  { label: 'ℷ', latex: '\\gimel', category: 'Symbols', tooltip: 'Gimel', scale: 1.8 },
  { label: 'ℸ', latex: '\\daleth', category: 'Symbols', tooltip: 'Daleth', scale: 1.8 },
  { label: '⅁', latex: '\\Game', category: 'Symbols', tooltip: 'Game Symbol', scale: 1.8 },
  { label: 'Ⅎ', latex: '\\Finv', category: 'Symbols', tooltip: 'Finv Symbol', scale: 1.8 },
  { label: '∁', latex: '\\complement', category: 'Symbols', tooltip: 'Set Complement', scale: 1.8 },
  { label: 'ℵ', latex: '\\alefsym', category: 'Symbols', tooltip: 'Aleph Symbol', scale: 1.8 },
  { label: 'digamma', latex: '\\digamma', category: 'Symbols', tooltip: 'Digamma', scale: 1.8 },
  { label: 'varkappa', latex: '\\varkappa', category: 'Symbols', tooltip: 'Varkappa', scale: 1.8 },
  { label: '□', latex: '\\Box', category: 'Symbols', tooltip: 'Square', scale: 1.8 },
  { label: '⋄', latex: '\\Diamond', category: 'Symbols', tooltip: 'Diamond', scale: 1.8 },
  { label: '◯', latex: '\\bigcirc', category: 'Symbols', tooltip: 'Circle', scale: 1.8 },
  { label: '△', latex: '\\triangle', category: 'Symbols', tooltip: 'Triangle', scale: 1.8 },
  { label: '¬', latex: '\\neg', category: 'Symbols', tooltip: 'Negation', scale: 2 },
  { label: '∴', latex: '\\therefore', category: 'Symbols', tooltip: 'Therefore', scale: 2 },
  { label: '∵', latex: '\\because', category: 'Symbols', tooltip: 'Because', scale: 2 },
  { label: '⊤', latex: '\\top', category: 'Symbols', tooltip: 'Top / Tautology', scale: 1.8 },
  { label: '⊥', latex: '\\bot', category: 'Symbols', tooltip: 'Bottom / Contradiction', scale: 1.8 },
  { label: 'ℝ', latex: '\\mathbb{R}', category: 'Symbols', tooltip: 'Real Numbers', scale: 1.8 },
  { label: 'ℂ', latex: '\\mathbb{C}', category: 'Symbols', tooltip: 'Complex Numbers', scale: 1.8 },
  { label: 'ℕ', latex: '\\mathbb{N}', category: 'Symbols', tooltip: 'Natural Numbers', scale: 1.8 },
  { label: 'ℤ', latex: '\\mathbb{Z}', category: 'Symbols', tooltip: 'Integers', scale: 1.8 },
  { label: 'ℚ', latex: '\\mathbb{Q}', category: 'Symbols', tooltip: 'Rational Numbers', scale: 1.8 },
  { label: '⋯', latex: '\\cdots', category: 'Symbols', tooltip: 'Horizontal Dots', scale: 1.8 },
  { label: '⋮', latex: '\\vdots', category: 'Symbols', tooltip: 'Vertical Dots', scale: 1.8 },
  { label: '⋱', latex: '\\ddots', category: 'Symbols', tooltip: 'Diagonal Dots', scale: 1.8 },
  { label: '°', latex: '^{\\circ}', category: 'Symbols', tooltip: 'Degree', scale: 1.8 },
  { label: '✓', latex: '\\checkmark', category: 'Symbols', tooltip: 'Checkmark', scale: 1.8 },

  // --- GREEK ---
  { label: 'α', latex: '\\alpha', category: 'Greek', tooltip: 'alpha', scale: 2 },
  { label: 'β', latex: '\\beta', category: 'Greek', tooltip: 'beta', scale: 2 },
  { label: 'γ', latex: '\\gamma', category: 'Greek', tooltip: 'gamma', scale: 2 },
  { label: 'δ', latex: '\\delta', category: 'Greek', tooltip: 'delta', scale: 2 },
  { label: 'ε', latex: '\\epsilon', category: 'Greek', tooltip: 'epsilon', scale: 2 },
  { label: 'ζ', latex: '\\zeta', category: 'Greek', tooltip: 'zeta', scale: 2 },
  { label: 'η', latex: '\\eta', category: 'Greek', tooltip: 'eta', scale: 2 },
  { label: 'θ', latex: '\\theta', category: 'Greek', tooltip: 'theta', scale: 2 },
  { label: 'ι', latex: '\\iota', category: 'Greek', tooltip: 'iota', scale: 2 },
  { label: 'κ', latex: '\\kappa', category: 'Greek', tooltip: 'kappa', scale: 2 },
  { label: 'λ', latex: '\\lambda', category: 'Greek', tooltip: 'lambda', scale: 2 },
  { label: 'μ', latex: '\\mu', category: 'Greek', tooltip: 'mu', scale: 2 },
  { label: 'ν', latex: '\\nu', category: 'Greek', tooltip: 'nu', scale: 2 },
  { label: 'ξ', latex: '\\xi', category: 'Greek', tooltip: 'xi', scale: 2 },
  { label: 'π', latex: '\\pi', category: 'Greek', tooltip: 'pi', scale: 2 },
  { label: 'ρ', latex: '\\rho', category: 'Greek', tooltip: 'rho', scale: 2 },
  { label: 'σ', latex: '\\sigma', category: 'Greek', tooltip: 'sigma', scale: 2 },
  { label: 'τ', latex: '\\tau', category: 'Greek', tooltip: 'tau', scale: 2 },
  { label: 'υ', latex: '\\upsilon', category: 'Greek', tooltip: 'upsilon', scale: 2 },
  { label: 'φ', latex: '\\phi', category: 'Greek', tooltip: 'phi', scale: 2 },
  { label: 'χ', latex: '\\chi', category: 'Greek', tooltip: 'chi', scale: 2 },
  { label: 'ψ', latex: '\\psi', category: 'Greek', tooltip: 'psi', scale: 2 },
  { label: 'ω', latex: '\\omega', category: 'Greek', tooltip: 'omega', scale: 2 },
  { label: 'ε', latex: '\\varepsilon', category: 'Greek', tooltip: 'varepsilon', scale: 2 },
  { label: 'ϑ', latex: '\\vartheta', category: 'Greek', tooltip: 'vartheta', scale: 2 },
  { label: 'ϕ', latex: '\\varphi', category: 'Greek', tooltip: 'varphi', scale: 2 },
  { label: 'ϖ', latex: '\\varpi', category: 'Greek', tooltip: 'varpi', scale: 2 },
  { label: 'ϱ', latex: '\\varrho', category: 'Greek', tooltip: 'varrho', scale: 2 },
  { label: 'ς', latex: '\\varsigma', category: 'Greek', tooltip: 'varsigma', scale: 2 },
  { label: 'Γ', latex: '\\Gamma', category: 'Greek', tooltip: 'Gamma', scale: 2 },
  { label: 'Δ', latex: '\\Delta', category: 'Greek', tooltip: 'Delta', scale: 2 },
  { label: 'Θ', latex: '\\Theta', category: 'Greek', tooltip: 'Theta', scale: 2 },
  { label: 'Λ', latex: '\\Lambda', category: 'Greek', tooltip: 'Lambda', scale: 2 },
  { label: 'Ξ', latex: '\\Xi', category: 'Greek', tooltip: 'Xi', scale: 2 },
  { label: 'Π', latex: '\\Pi', category: 'Greek', tooltip: 'Pi', scale: 2 },
  { label: 'Σ', latex: '\\Sigma', category: 'Greek', tooltip: 'Sigma', scale: 2 },
  { label: 'Φ', latex: '\\Phi', category: 'Greek', tooltip: 'Phi', scale: 2 },
  { label: 'Ψ', latex: '\\Psi', category: 'Greek', tooltip: 'Psi', scale: 2 },
  { label: 'Ω', latex: '\\Omega', category: 'Greek', tooltip: 'Omega', scale: 2 },

  // --- FONTS ---
  { label: 'bb', latex: '\\mathbb{X}', category: 'Fonts', tooltip: 'Blackboard Bold', scale: 1.8 },
  { label: 'cal', latex: '\\mathcal{X}', category: 'Fonts', tooltip: 'Calligraphic', scale: 1.8 },
  { label: 'frak', latex: '\\mathfrak{X}', category: 'Fonts', tooltip: 'Fraktur', scale: 1.8 },
  { label: 'scr', latex: '\\mathscr{X}', category: 'Fonts', tooltip: 'Script', scale: 1.8 },
  { label: 'bold', latex: '\\mathbf{x}', category: 'Fonts', tooltip: 'Bold', scale: 1.8 },
  { label: 'italic', latex: '\\mathit{x}', category: 'Fonts', tooltip: 'Italic', scale: 1.8 },
  { label: 'roman', latex: '\\mathrm{x}', category: 'Fonts', tooltip: 'Roman', scale: 1.8 },
  { label: 'sans', latex: '\\mathsf{x}', category: 'Fonts', tooltip: 'Sans-Serif', scale: 1.8 },
  { label: 'mono', latex: '\\mathtt{x}', category: 'Fonts', tooltip: 'Monospace', scale: 1.8 },
  { label: 'text', latex: '\\text{abc}', category: 'Fonts', tooltip: 'Plain Text', scale: 1.4 },

  // --- MATRICES ---
  { label: 'matrix', latex: '\\begin{matrix} a & b \\\\ c & d \\end{matrix}', category: 'Matrices', tooltip: 'Matrix', scale: 0.9 },
  { label: 'pmatrix', latex: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}', category: 'Matrices', tooltip: 'Parentheses Matrix', scale: 0.9 },
  { label: 'bmatrix', latex: '\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}', category: 'Matrices', tooltip: 'Bracket Matrix', scale: 0.9 },
  { label: 'vmatrix', latex: '\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}', category: 'Matrices', tooltip: 'Determinant Matrix', scale: 0.9 },
  { label: 'Vmatrix', latex: '\\begin{Vmatrix} a & b \\\\ c & d \\end{Vmatrix}', category: 'Matrices', tooltip: 'Norm Matrix', scale: 0.9 },
  { label: 'Bmatrix', latex: '\\begin{Bmatrix} a & b \\\\ c & d \\end{Bmatrix}', category: 'Matrices', tooltip: 'Braces Matrix', scale: 0.9 },
  { label: 'small', latex: '\\begin{smallmatrix} a & b \\\\ c & d \\end{smallmatrix}', category: 'Matrices', tooltip: 'Small Matrix', scale: 1.6 },

  // --- ENVIRONMENTS ---
  { label: 'cases', latex: '\\begin{cases} x & x > 0 \\\\ -x & x \\le 0 \\end{cases}', category: 'Environments', tooltip: 'Cases', scale: 0.75 },
  { label: 'rcases', latex: '\\begin{rcases} x & x > 0 \\\\ -x & x \\le 0 \\end{rcases}', category: 'Environments', tooltip: 'Reverse Cases', scale: 0.75 },
  { label: 'aligned', latex: '\\begin{aligned} a &= b \\\\ c &= d \\end{aligned}', category: 'Environments', tooltip: 'Aligned Equations', scale: 0.9 },
  { label: 'array', latex: '\\begin{array}{cc} a & b \\\\ c & d \\end{array}', category: 'Environments', tooltip: 'Array', scale: 0.9 },
  { label: 'gather', latex: '\\begin{gathered} a = b \\\\ c = d \\end{gathered}', category: 'Environments', tooltip: 'Gathered Equations', scale: 0.9 },
  { label: 'boxed', latex: '\\boxed{x}', category: 'Environments', tooltip: 'Boxed Expression', scale: 1.4 },
  { label: 'cancel', latex: '\\cancel{x}', category: 'Environments', tooltip: 'Strikethrough', scale: 1.4 },
  { label: 'bcancel', latex: '\\bcancel{x}', category: 'Environments', tooltip: 'Back Strikethrough', scale: 1.4 },
  { label: 'xcancel', latex: '\\xcancel{x}', category: 'Environments', tooltip: 'Cross Strikethrough', scale: 1.4 },

  // --- ACCENTS & OVERSET ---
  { label: 'dot', latex: '\\dot{x}', category: 'Accents', tooltip: 'Dot', scale: 2 },
  { label: 'ddot', latex: '\\ddot{x}', category: 'Accents', tooltip: 'Double Dot', scale: 2 },
  { label: 'dddot', latex: '\\dddot{x}', category: 'Accents', tooltip: 'Triple Dot', scale: 2 },
  { label: 'ddddot', latex: '\\ddddot{x}', category: 'Accents', tooltip: 'Quad Dot', scale: 2 },
  { label: 'mathring', latex: '\\mathring{x}', category: 'Accents', tooltip: 'Ring Accent', scale: 2 },
  { label: 'widecheck', latex: '\\widecheck{xyz}', category: 'Accents', tooltip: 'Wide Check', scale: 1.6 },
  { label: 'bar', latex: '\\bar{x}', category: 'Accents', tooltip: 'Bar', scale: 2 },
  { label: 'hat', latex: '\\hat{x}', category: 'Accents', tooltip: 'Hat', scale: 2 },
  { label: 'vec', latex: '\\vec{x}', category: 'Accents', tooltip: 'Vector', scale: 2 },
  { label: 'tilde', latex: '\\tilde{x}', category: 'Accents', tooltip: 'Tilde', scale: 2 },
  { label: 'overline', latex: '\\overline{xyz}', category: 'Accents', tooltip: 'Overline', scale: 1.4 },
  { label: 'underline', latex: '\\underline{xyz}', category: 'Accents', tooltip: 'Underline', scale: 1.4 },
  { label: 'overbrace', latex: '\\overbrace{abc}', category: 'Accents', tooltip: 'Overbrace', scale: 1.4 },
  { label: 'underbrace', latex: '\\underbrace{abc}', category: 'Accents', tooltip: 'Underbrace', scale: 1.4 },
  { label: 'overgroup', latex: '\\overgroup{abc}', category: 'Accents', tooltip: 'Overgroup', scale: 1.4 },
  { label: 'undergroup', latex: '\\undergroup{abc}', category: 'Accents', tooltip: 'Undergroup', scale: 1.4 },
  { label: 'overbracket', latex: '\\overbracket{abc}', category: 'Accents', tooltip: 'Overbracket', scale: 1.4 },
  { label: 'underbracket', latex: '\\underbracket{abc}', category: 'Accents', tooltip: 'Underbracket', scale: 1.4 },
  { label: 'vec arrow', latex: '\\overrightarrow{abc}', category: 'Accents', tooltip: 'Over Right Arrow', scale: 1.4 },
  { label: 'under arrow', latex: '\\underrightarrow{abc}', category: 'Accents', tooltip: 'Under Right Arrow', scale: 1.4 },
  { label: 'overset', latex: '\\overset{abc}{AB}', category: 'Accents', tooltip: 'Overset', scale: 1.4 },
  { label: 'underset', latex: '\\underset{abc}{AB}', category: 'Accents', tooltip: 'Underset', scale: 1.4 }
] as const satisfies LaTeXSymbol[];
