export interface LaTeXSymbol {
  label: string;
  latex: string;
  category: string;
  tooltip: string;
}

export const LATEX_CATEGORIES = [
  'Functions',
  'Operators',
  'Relations',
  'Arrows',
  'Brackets',
  'Symbols',
  'Fonts',
  'Greek',
  'Matrices',
  'Environments',
  'Accents'
];

export const LATEX_SYMBOLS: LaTeXSymbol[] = [
  // FUNCTIONS
  { label: 'Fraction', latex: '\\frac{a}{b}', category: 'Functions', tooltip: 'Fraction: \\frac{num}{den}' },
  { label: 'Sqrt', latex: '\\sqrt{x}', category: 'Functions', tooltip: 'Square Root: \\sqrt{x}' },
  { label: 'n-th Sqrt', latex: '\\sqrt[n]{x}', category: 'Functions', tooltip: 'n-th Root: \\sqrt[n]{x}' },
  { label: 'Exponent', latex: 'x^{n}', category: 'Functions', tooltip: 'Exponent/Superscript: x^n' },
  { label: 'Subscript', latex: 'x_{n}', category: 'Functions', tooltip: 'Subscript: x_n' },
  { label: 'Log', latex: '\\log_{b}(x)', category: 'Functions', tooltip: 'Logarithm: \\log_b(x)' },
  { label: 'Ln', latex: '\\ln(x)', category: 'Functions', tooltip: 'Natural Logarithm: \\ln(x)' },
  { label: 'Limit', latex: '\\lim_{x \\to \\infty}', category: 'Functions', tooltip: 'Limit: \\lim' },
  { label: 'Sum', latex: '\\sum_{i=1}^{n}', category: 'Functions', tooltip: 'Summation: \\sum' },
  { label: 'Product', latex: '\\prod_{i=1}^{n}', category: 'Functions', tooltip: 'Product: \\prod' },
  { label: 'Integral', latex: '\\int_{a}^{b}', category: 'Functions', tooltip: 'Definite Integral: \\int' },
  { label: 'Double Int', latex: '\\iint_{D}', category: 'Functions', tooltip: 'Double Integral: \\iint' },
  { label: 'Triple Int', latex: '\\iiint_{V}', category: 'Functions', tooltip: 'Triple Integral: \\iiint' },
  { label: 'Contour Int', latex: '\\oint_{C}', category: 'Functions', tooltip: 'Contour Integral: \\oint' },
  { label: 'Partial', latex: '\\partial', category: 'Functions', tooltip: 'Partial: \\partial' },
  { label: 'Derivative', latex: '\\frac{dy}{dx}', category: 'Functions', tooltip: 'Derivative: \\frac{dy}{dx}' },
  { label: 'sin', latex: '\\sin', category: 'Functions', tooltip: 'Sine' },
  { label: 'cos', latex: '\\cos', category: 'Functions', tooltip: 'Cosine' },
  { label: 'tan', latex: '\\tan', category: 'Functions', tooltip: 'Tangent' },
  { label: 'cot', latex: '\\cot', category: 'Functions', tooltip: 'Cotangent' },
  { label: 'sec', latex: '\\sec', category: 'Functions', tooltip: 'Secant' },
  { label: 'csc', latex: '\\csc', category: 'Functions', tooltip: 'Cosecant' },
  { label: 'arcsin', latex: '\\arcsin', category: 'Functions', tooltip: 'Arcsine' },
  { label: 'arccos', latex: '\\arccos', category: 'Functions', tooltip: 'Arccosine' },
  { label: 'arctan', latex: '\\arctan', category: 'Functions', tooltip: 'Arctangent' },
  { label: 'sinh', latex: '\\sinh', category: 'Functions', tooltip: 'Hyperbolic Sine' },
  { label: 'cosh', latex: '\\cosh', category: 'Functions', tooltip: 'Hyperbolic Cosine' },
  { label: 'tanh', latex: '\\tanh', category: 'Functions', tooltip: 'Hyperbolic Tangent' },
  { label: 'exp', latex: '\\exp', category: 'Functions', tooltip: 'Exponential function' },
  { label: 'max', latex: '\\max', category: 'Functions', tooltip: 'Maximum' },
  { label: 'min', latex: '\\min', category: 'Functions', tooltip: 'Minimum' },
  { label: 'sup', latex: '\\sup', category: 'Functions', tooltip: 'Supremum' },
  { label: 'inf', latex: '\\inf', category: 'Functions', tooltip: 'Infimum' },
  { label: 'arg', latex: '\\arg', category: 'Functions', tooltip: 'Argument' },
  { label: 'deg', latex: '\\deg', category: 'Functions', tooltip: 'Degree' },
  { label: 'det', latex: '\\det', category: 'Functions', tooltip: 'Determinant' },
  { label: 'dim', latex: '\\dim', category: 'Functions', tooltip: 'Dimension' },
  { label: 'gcd', latex: '\\gcd', category: 'Functions', tooltip: 'Greatest Common Divisor' },
  { label: 'ker', latex: '\\ker', category: 'Functions', tooltip: 'Kernel' },
  { label: 'lg', latex: '\\lg', category: 'Functions', tooltip: 'Binary Logarithm' },
  { label: 'Pr', latex: '\\Pr', category: 'Functions', tooltip: 'Probability' },

  // OPERATORS
  { label: '+', latex: '+', category: 'Operators', tooltip: 'Add' },
  { label: '-', latex: '-', category: 'Operators', tooltip: 'Subtract' },
  { label: '±', latex: '\\pm', category: 'Operators', tooltip: 'Plus-Minus' },
  { label: '∓', latex: '\\mp', category: 'Operators', tooltip: 'Minus-Plus' },
  { label: '×', latex: '\\times', category: 'Operators', tooltip: 'Multiplication (Cross)' },
  { label: '÷', latex: '\\div', category: 'Operators', tooltip: 'Division' },
  { label: '⋅', latex: '\\cdot', category: 'Operators', tooltip: 'Dot Product' },
  { label: '∗', latex: '\\ast', category: 'Operators', tooltip: 'Asterisk Operator' },
  { label: '⋆', latex: '\\star', category: 'Operators', tooltip: 'Star Operator' },
  { label: '∘', latex: '\\circ', category: 'Operators', tooltip: 'Composition/Function Circle' },
  { label: '∙', latex: '\\bullet', category: 'Operators', tooltip: 'Bullet Point' },
  { label: '⊕', latex: '\\oplus', category: 'Operators', tooltip: 'Direct Sum' },
  { label: '⊖', latex: '\\ominus', category: 'Operators', tooltip: 'Circled Minus' },
  { label: '⊗', latex: '\\otimes', category: 'Operators', tooltip: 'Tensor Product' },
  { label: '⊘', latex: '\\oslash', category: 'Operators', tooltip: 'Circled Slash' },
  { label: '⊙', latex: '\\odot', category: 'Operators', tooltip: 'Circled Dot' },
  { label: '†', latex: '\\dagger', category: 'Operators', tooltip: 'Dagger' },
  { label: '‡', latex: '\\ddagger', category: 'Operators', tooltip: 'Double Dagger' },
  { label: '∨', latex: '\\vee', category: 'Operators', tooltip: 'Logical OR / Join' },
  { label: '∧', latex: '\\wedge', category: 'Operators', tooltip: 'Logical AND / Meet' },
  { label: '∩', latex: '\\cap', category: 'Operators', tooltip: 'Intersection' },
  { label: '∪', latex: '\\cup', category: 'Operators', tooltip: 'Union' },
  { label: '⊎', latex: '\\uplus', category: 'Operators', tooltip: 'Multiset Union' },
  { label: '⊓', latex: '\\sqcap', category: 'Operators', tooltip: 'Square Cap' },
  { label: '⊔', latex: '\\sqcup', category: 'Operators', tooltip: 'Square Cup' },
  { label: '∖', latex: '\\setminus', category: 'Operators', tooltip: 'Set Minus' },
  { label: '≀', latex: '\\wr', category: 'Operators', tooltip: 'Wreath Product' },
  { label: '∐', latex: '\\amalg', category: 'Operators', tooltip: 'Amalgamation/Coproduct' },
  { label: '△', latex: '\\triangle', category: 'Operators', tooltip: 'Symmetric Difference' },
  { label: '▽', latex: '\\triangledown', category: 'Operators', tooltip: 'Triangle Down Operator' },
  { label: '◁', latex: '\\triangleleft', category: 'Operators', tooltip: 'Triangle Left Operator' },
  { label: '▷', latex: '\\triangleright', category: 'Operators', tooltip: 'Triangle Right Operator' }
];
